[#21] chore: 회원가입 화면 구성 완료
manOfBackend/everyone-s-party pull request #26
Opened 2022-05-14 12:24 UTC by parkyw1206

2022-05-16 14:30 UTC, parkyw1206 commented
지난 번에 리뷰해주신대로 버튼 컴포넌트를 기존 버튼을 활용해보았습니다. 확인 부탁드립니다. @manOfBackend

2022-05-17 02:24 UTC, manOfBackend requested changes
수정이 필요한 부분 코멘트 남겼습니다 :)

2022-05-17 02:24 UTC, manOfBackend commented on src/components/atoms/ButtonCTA/index.tsx
> +  handleSubmit?: (e?: React.FormEvent<HTMLFormElement>) => void;
밑에는 onClick인데 여긴 handleSubmit이네요.
인터페이스에선 handle보단 on~으로 통일할게요.

2022-05-17 02:24 UTC, manOfBackend commented on src/components/atoms/LoginTextField/index.tsx
> +import React from 'react';
Atom 컴포넌트를 1개 이상 사용해서 만들었다면 molecules로 보내주세요 :)

2022-05-17 02:24 UTC, manOfBackend commented on src/components/atoms/LoginTextField/style.ts
> +export const LoginInput = styled(TextField)`
좀 더 공용 컴포넌트로 사용할 수 있도록 인터페이스를 추가했으면 좋을 것 같아요.
높이, 너비 같은 것들요.
아래 제 코드를 참고해주세요 :)
```
import { css } from '@emotion/core';
import styled from '@emotion/styled';

interface BarProps {
    width: string;
    barColor: string;
    marginTop?: number;
}

export const Bar = styled.div<BarProps>(
  ({ width, barColor, marginTop }) => css`
      height: 1px;
      background-color: ${barColor};
      width: ${width};
      border-top-left-radius: 10%;
      border-top-right-radius: 10%;
      ${marginTop && css`
        margin-top: ${marginTop + 50};
      `}
    `,
);
```

2022-05-17 02:24 UTC, manOfBackend commented on src/pages/Signup/index.tsx
> +                <button
여기도 버튼을 컴포넌트로 변경하면 좋을 것 같습니다.

2022-05-18 12:56 UTC, parkyw1206 commented on src/components/atoms/ButtonCTA/index.tsx
> +  handleSubmit?: (e?: React.FormEvent<HTMLFormElement>) => void;
같은 버튼이여도 submit type인 경우에 handleSubmit 을 사용했는데, on~으로 통일하였으니 버튼이 submit일 경우 onSubmit, 일반 button일 경우, onClick을 사용합니다.

2022-05-18 13:00 UTC, parkyw1206 commented on src/components/atoms/LoginTextField/index.tsx
> +import React from 'react';
네. 수정하였습니다.

2022-05-18 13:08 UTC, parkyw1206 commented on src/components/atoms/LoginTextField/style.ts
> +export const LoginInput = styled(TextField)`
해당 컴포넌트에 height, width,그리고 focus되었을 경우의 색, 총 3가지 인터페이스를 추가했습니다.

2022-05-18 13:36 UTC, manOfBackend approved these changes
고생하셨습니다!! 👍 😄

2022-05-18 13:37 UTC, merged